// Canonical data contract for Charles AI Studios — the Cake Tower.
// SINGLE SOURCE OF TRUTH for the studio shape. The composer re-exports this
// (composer/src/types.ts) so the studios.json it writes always matches what the
// app reads. Two layers: the human-authored Manifest, and the machine-derived
// Status — merged by `id` into a Studio.

export type Stage = "alpha" | "beta" | "live" | "coming-soon";

/** Districts double as cake tiers (HQ is the topper). */
export type District = "AEO" | "Enablement" | "Research" | "Attribution" | "HQ";

/** One health rule for every studio. `coming-soon` short-circuits the rest. */
export type Health = "ok" | "working" | "attention" | "stale" | "down" | "coming-soon";

/** Out-links shown in the inspector. All optional; `launch` drives the launch button. */
export interface Links {
  launch?: string;
  repo?: string;
  project?: string; // Linear project URL
  dashboard?: string;
  figma?: string;
}

/** Where live data is pulled FROM. Absent for coming-soon studios. */
export interface Sources {
  /** Linear project id — captured during Job A seeding. */
  linearProjectId?: string;
  /** owner/repo on GitHub, e.g. "charleslim-ps/ai-vis". */
  repo?: string;
}

// ── Layer 1: Manifest (HUMAN-authored, manifests/<id>.json, slow-changing) ──
export interface Manifest {
  /** Stable slug + canonical join key. */
  id: string;
  name: string;
  purpose: string;
  stage: Stage;
  district: District;
  /** Vertical order in the cake (lower = higher up; HQ tier is the topper). */
  tier: number;
  /** Order within the tier, left→right. */
  slot: number;
  /** Filename under app/public/assets/studios/. Optional → placeholder room. */
  studioAsset?: string;
  /** Studio ids this one depends on — draws the wires between rooms. */
  depends_on?: string[];
  links?: Links;
  sources?: Sources;
}

// ── Layer 2: Status (MACHINE-generated by the composer, never hand-edited) ──
export interface RunSignal {
  status: "success" | "failure" | "in_progress" | "unknown";
  at: string | null; // ISO
}

export interface Signals {
  lastRun: RunSignal;
  deploy: RunSignal;
  /** Days since the most recent observed activity. */
  freshnessDays: number | null;
  /** Beyond this, the studio is `stale`. */
  expectedCadenceDays: number;
}

export interface RoadmapItem {
  title: string;
  state: string;
}

export interface Todo {
  title: string;
  state: string;
  priority?: number;
  link?: string;
}

export interface Activity {
  at: string; // ISO
  type: "commit" | "push" | "run" | "deploy" | string;
  summary: string;
  link?: string;
}

export interface Status {
  health: Health;
  signals: Signals;
  roadmap: RoadmapItem[];
  todos: Todo[];
  activity: Activity[];
  generatedAt: string;
}

// ── Merged: what the app actually renders ──
export type Studio = Manifest & Status;

/** The composed file the app fetches. */
export interface StudiosFile {
  generatedAt: string;
  studios: Studio[];
}
